version: "3.5"
services:
  fitfriends.mongo:
    image: mongo
    restart: always
    container_name: fitfriends.mongo
    env_file:
      - .mongo.env
    volumes:
      - fitfriends.app.volume:/data/db
    networks:
      - fitfriends.app.network

  fitfriends.mongo.ui:
    image: mongo-express
    depends_on:
      - fitfriends.mongo
    restart: always
    container_name: fitfriends.mongo.ui
    env_file:
      - .mongo.ui.env
    ports:
      - 8081:8081
    networks:
      - fitfriends.app.network

  fitfriends.app.fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: fitfriends.fakesmtp
    hostname: fakesmtp
    restart: always
    networks:
      - fitfriends.app.network
    ports:
      - 1082:8080

  fitfriends.app:
    image: fitfriends.app:latest
    container_name: fitfriends.app
    depends_on:
      - fitfriends.mongo
    restart: always
    env_file:
      - .app.env
    networks:
      - fitfriends.app.network
    ports:
      - 3333:3333

  fitfriends.client:
    image: fitfriends.client:latest
    container_name: fitfriends.client
    depends_on:
      - fitfriends.app
    restart: always
    ports:
      - 3000:80

networks:
  fitfriends.app.network:
    driver: bridge

volumes:
  fitfriends.app.volume:
